name: 🐞 Bug Report
description: Report something that is not working correctly
labels: ["bug", ":mag_right: triage"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error...
  validations:
    required: true
- type: input
  attributes:
    label: Version
    description: |
      The version of AIMCADEMY where you experienced the bug.

      Tip: You can see the current version of AIMCADEMY in the main menu near the screen border. Click it to copy the text to your clipboard.
    placeholder: e.g. v0.5.1
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: |
      Log files? Links? References? Anything that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
