blank_issues_enabled: false
contact_links:
  - name: Aimcademy Discord
    url: http://discord.aimcademy.gg
    about: "Please ask and answer questions on our Discord server. GitHub issues aren't for questions."