name: 🌱 Suggestion
description: Suggest an idea
labels: ["suggestion", ":mag_right: triage"]
body:
- type: textarea
  attributes:
    label: Describe your idea
    description: A clear and concise description of what the problem is.
    placeholder: |
      e.g. I'm always frustrated when...

      e.g. It would make using AIMCADEMY easier if...
  validations:
    required: true